# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: agent  # Set the pool name as "agent"
  vmImage: ubuntu-latest

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  pool:
    name: agent  # Specify the pool for this job
  demands:
    - agent.name -equals agent1  # Specify the agent name for this job
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
